### ISSUE TITLE
Feature Request: Flexible duration from helper

### ISSUE THREAD

**Issue by PetziAt** [mampfes/ha_epex_spot_sensor#10]
I like to request an alternate duration input based on an selectable (input_datetime) helper. This makes possible to include the duration offered from an device.

**Comment by mampfes** [comment]
This is a valid request. I need to check how much effort it is.

**Comment by grol-hass** [comment]
I have implemented that in my fork just after the initial revision of this sensor came out:
https://github.com/grol-hass/ha_epex_spot_sensor_variable_duration
Feel free to pull the changes from there.
(I'm using it to determine when to charge my home battery from grid, that's why I also added code to make sure intermittent time slots are adjacent if possible)

**Comment by mampfes** [comment]
@grol-hass Thanks for sharing. I will use this a template.
